version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: fix(deps)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: fix(deps)
