version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "juissi-t"
  commit-message:
    prefix: chore
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "juissi-t"
  commit-message:
    prefix: chore
