name: Python package

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.9, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U .\[dev]
    - name: Test with pytest
      run: |
        pytest

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U .
    - uses: marian-code/python-lint-annotate@v3
      with:
        python-root-list: "./in_game_messages"
        extra-pycodestyle-options: "--max-line-length=88"
        extra-flake8-options: "--max-line-length=88"
        extra-vulture-options: "vulture_whitelist.py"
