name: Build and test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U .\[dev]
      - name: Test with pytest
        run: |
          pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Generate requirements.txt file
        run: |
          pip install -U .
          pip freeze > requirements.txt
      - uses: juissi-t/python-lint-annotate@bfd6c91105371fedb8a7675f7cc172582fe3925e
        with:
          python-version: "3.13"
          python-root-list: "./in_game_messages"
          extra-pycodestyle-options: "--max-line-length=88"
          extra-flake8-options: "--max-line-length=88"
          extra-vulture-options: "vulture_whitelist.py"
