name: Build and test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', 3.9, 3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U .\[dev]
    - name: Test with pytest
      run: |
        pytest

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Generate requirements.txt file
      run: |
        pip install -U .
        pip freeze > requirements.txt
    - uses: juissi-t/python-lint-annotate@ff09bc6bdd47de544b00cf57a9921c636a829909
      with:
        python-version: "3.10"
        python-root-list: "./in_game_messages"
        extra-pycodestyle-options: "--max-line-length=88"
        extra-flake8-options: "--max-line-length=88"
        extra-vulture-options: "vulture_whitelist.py"
